export enum ContactSource {
  MANUAL = "MANUAL",
  CSV_UPLOAD = "CSV_UPLOAD",
  HUBSPOT = "HUBSPOT",
  GBP = "GBP",
  ZOHO = "ZOHO",
  PIPEDRIVE = "PIPEDRIVE",
  SALESFORCE = "SALESFORCE",
  ACTIVE_CAMPAIGN = "ACTIVE_CAMPAIGN",
  SHOPIFY = "SHOPIFY",
}
